version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_DATABASE: redin
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: jesus
      MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306
  rsphp:
    image: rsphp
    ports:
      - "80:80"
    restart: always
    links:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 