pipeline {
    environment{
        registro="jlvd07/rsphp"
        registroID="jlvd07"
        dockerImage=""
    }
    agent any
    stages {
        stage('Construir rsphp'){
            steps{
                sh 'cd code && docker-compose down'
                sh 'docker image rm rsphp'
                sh 'cd code && docker build --tag=rsphp .'
                sh 'docker images'
            }
        }
        stage('Construir servicio rsphp + mysql'){
            steps{
                sh 'cd code && docker-compose up -d'
            }
        }
    }
}